apiVersion: v1
kind: Service
metadata:
  name: svc-beetroot
  namespace: beetroot
spec:
  selector:
    app: beetroot
  ports:
    - protocol:
      port: 8080
      targetPort: 8080
      nodePort: 30099