apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server
spec:
  type: NodePort
ports:
    - protocol: 
    port: 80
    targetPort: 8080
    - protocol: 
    port: 443
    targetPort: 8080
    nodeport: 30042
  selector:
    app.kubernetes.io/name: argocd-server
