apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-apache-beetroot
  namespace: argocd-beetroot
  labels:
    app: apache-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-argocd
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-argocd
          image: httpd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-conf
              mountPath: /usr/local/apache2/conf/
      volumes:
      - name: apache-conf
        configMap:
          name: apache-config-map