apiVersion: v1
kind: Service
metadata:
  name: svc-argocd-apache-beetroot
  namespace: argocd-beetroot
spec:
  type: NodePort
  selector:
    app: apache-argocd
  ports:
    - protocol:
      port: 80
      targetPort: 80
      nodePort: 30096