apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index-config-map
  namespace: argocd-apache-dev
data:
  index.html: |
    <html><body><h1>The prod environment is created and working fine</h1></body></html>