apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-apache-prod
  namespace: argocd-apache-prod
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
