apiVersion: v1
kind: Service
metadata:
  name: svc-argocd-apache-prod
  namespace: argocd-apache-prod
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - protocol:
      port: 80
      targetPort: 80
      nodePort: 30090