apiVersion: v1
kind: Service
metadata:
  name: svc-argocd-nginx-dev
  namespace: argocd-nginx-dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol:
      port: 80
      targetPort: 80
      nodePort: 30093